import { Ionicons } from '@expo/vector-icons';
import { router, Stack, useLocalSearchParams } from 'expo-router';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, EmptyState, Orb, Screen } from '@/src/components/ui';
import { useAppState } from '@/src/state/AppState';
import { colors } from '@/src/theme';
const actions = [{ icon:'chatbubble-outline',label:'Message'},{icon:'call-outline',label:'Call'},{icon:'key-outline',label:'Check-in Details'},{icon:'create-outline',label:'Modify Booking'}] as const;
export default function BookingDetail() { const { id } = useLocalSearchParams<{id:string}>(); const { bookings, properties, conversations, setAssistantDraft } = useAppState(); const b=bookings.find(x=>x.id===id); if(!b) return <Screen><EmptyState icon="calendar-outline" title="Booking not found" body="This sample stay is no longer available." /></Screen>; const p=properties.find(x=>x.id===b.propertyId); const ask=(text:string)=>{setAssistantDraft(text);router.push('/ai')}; return <Screen><Stack.Screen options={{headerShown:false}}/><View style={styles.hero}><Image source={p?.image} style={styles.image}/><Pressable accessibilityLabel="Back" onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.ink}/></Pressable><Text style={styles.heroLabel}>{p?.name}</Text></View><View style={styles.heading}><View><Text style={styles.name}>{b.guest}</Text><Text style={styles.status}>{b.status}</Text></View><View style={styles.avatar}><Text style={styles.initials}>{b.initials}</Text></View></View><Card style={styles.details}>{[['Check-in',b.checkIn],['Check-out',b.checkOut],['Guests',String(b.guests)],['Revenue',b.value]].map(([label,value],i)=><View key={label} style={[styles.detail,i>0&&styles.rule]}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}</Card><View style={styles.actions}>{actions.map(a=><Pressable key={a.label} onPress={()=>a.label==='Message'&&router.push(`/conversation/${conversations.find(c=>c.bookingId===b.id)?.id??'sarah'}`)} style={styles.action}><View style={styles.actionIcon}><Ionicons name={a.icon} size={20} color={colors.green}/></View><Text style={styles.actionText}>{a.label}</Text></Pressable>)}</View><Pressable onPress={()=>ask(`Tell me about ${b.guest}'s booking`)} style={styles.ask}><Orb size={36}/><Text style={styles.askText}>Ask Virtu about this booking</Text><Ionicons name="arrow-forward" color={colors.green} size={18}/></Pressable><Text style={styles.section}>Suggestions</Text>{['Send check-in instructions','Offer early check-in','Summarise conversation'].map(x=><Pressable key={x} onPress={()=>ask(x)} style={styles.suggestion}><Text style={styles.suggestionText}>{x}</Text><Ionicons name="chevron-forward" size={17} color={colors.inkFaint}/></Pressable>)}<Text style={styles.preview}>Sample booking details. No live channel changes will be made.</Text></Screen> }
const styles=StyleSheet.create({hero:{height:250,borderRadius:26,overflow:'hidden',backgroundColor:'#ddd'},image:{width:'100%',height:'100%'},back:{position:'absolute',top:14,left:14,width:44,height:44,borderRadius:22,backgroundColor:'rgba(255,255,255,.9)',alignItems:'center',justifyContent:'center'},heroLabel:{position:'absolute',left:18,bottom:17,color:'#fff',fontSize:14,fontWeight:'800'},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:21},name:{color:colors.ink,fontSize:28,fontWeight:'900',letterSpacing:-.7},status:{color:colors.green,fontSize:12,fontWeight:'700',marginTop:5},avatar:{width:48,height:48,borderRadius:24,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},initials:{color:colors.greenDark,fontWeight:'900'},details:{marginTop:18,paddingVertical:3},detail:{minHeight:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},rule:{borderTopWidth:1,borderTopColor:colors.line},label:{color:colors.inkMuted,fontSize:12},value:{color:colors.ink,fontSize:13,fontWeight:'800'},actions:{flexDirection:'row',justifyContent:'space-between',marginTop:21},action:{width:'24%',alignItems:'center'},actionIcon:{width:48,height:48,borderRadius:17,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},actionText:{color:colors.inkMuted,fontSize:10,textAlign:'center',marginTop:7},ask:{minHeight:64,borderRadius:21,backgroundColor:colors.glass,borderWidth:1,borderColor:'#fff',paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:11,marginTop:23},askText:{flex:1,color:colors.ink,fontSize:14,fontWeight:'700'},section:{color:colors.inkFaint,fontSize:10,fontWeight:'800',letterSpacing:1,textTransform:'uppercase',marginTop:25,marginBottom:5},suggestion:{minHeight:48,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},suggestionText:{color:colors.ink,fontSize:13,fontWeight:'600'},preview:{color:colors.inkFaint,fontSize:10,marginTop:18}})
