import { Ionicons } from '@expo/vector-icons';
import * as Linking from 'expo-linking';
import { router } from 'expo-router';
import { useRef } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ambient, Orb } from '@/src/components/ui';
import { useAppState } from '@/src/state/AppState';
import { whatsappConfig } from '@/src/config';
import { colors } from '@/src/theme';
import { useBottomNavClearance } from '@/src/layout';
const prompts = ["Who's arriving today?", 'Update my listing', 'Message a guest', 'Check availability'];
export default function AIScreen() {
  const state = useAppState(); const scroll = useRef<ScrollView>(null); const clearance = useBottomNavClearance();
  const submit = (value = state.assistantDraft) => { void state.sendAssistantMessage(value).then(() => setTimeout(() => scroll.current?.scrollToEnd({ animated: true }), 60)); };
  return <SafeAreaView style={styles.safe}><Ambient /><KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><Orb size={44} busy={state.assistantBusy} /><View><Text style={styles.title}>Virtu AI</Text><Text style={styles.status}>{state.assistantBusy ? 'Thinking…' : 'Your hosting assistant'}</Text></View></View><ScrollView ref={scroll} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    {state.messages.length === 0 ? <View style={styles.empty}><Orb size={68} /><Text style={styles.question}>What should we{`\n`}take care of?</Text><Text style={styles.helper}>Ask Virtu to manage bookings, guests, listings, pricing and more.</Text><View style={styles.suggestions}>{prompts.map((p) => <Pressable key={p} onPress={() => state.setAssistantDraft(p)} style={styles.suggestion}><Text style={styles.suggestionText}>{p}</Text></Pressable>)}</View><Text style={styles.demo}>Sample assistant. No live AI or booking provider is connected.</Text></View> : <View style={styles.thread}>{state.messages.map((m) => <View key={m.id} style={[styles.bubble, m.role === 'user' ? styles.user : styles.ai]}><Text style={[styles.message, m.role === 'user' && { color: '#fff' }]}>{m.text}</Text>{m.action && <Pressable onPress={() => router.push(m.action!.route as never)} style={styles.action}><Text style={styles.actionText}>{m.action.label}</Text><Ionicons name="arrow-forward" color={colors.green} size={16} /></Pressable>}</View>)}{state.assistantBusy && <View style={styles.thinking}><ActivityIndicator color={colors.green} /><Text style={styles.thinkingText}>Looking across your workspace</Text></View>}</View>}
  </ScrollView><View style={[styles.composerWrap, { paddingBottom: clearance }]}><View style={styles.composer}><Ionicons name="camera-outline" size={20} color={colors.inkFaint} /><TextInput accessibilityLabel="Ask Virtu" multiline value={state.assistantDraft} onChangeText={state.setAssistantDraft} placeholder="Ask Virtu…" placeholderTextColor={colors.inkFaint} style={styles.input} /><Pressable accessibilityRole="button" disabled={!state.assistantDraft.trim() || state.assistantBusy} onPress={() => submit()} style={styles.send}><Ionicons name="arrow-up" size={20} color="#fff" /></Pressable></View><Pressable onPress={() => Linking.openURL(whatsappConfig.url)} style={styles.whatsapp}><Ionicons name="logo-whatsapp" size={15} color={colors.green} /><Text style={styles.whatsappText}>Continue in WhatsApp</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { paddingHorizontal: 20, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', gap: 12, maxWidth: 640, width: '100%', alignSelf: 'center' }, title: { color: colors.ink, fontSize: 20, fontWeight: '900' }, status: { color: colors.green, fontSize: 12, marginTop: 3, fontWeight: '600' }, content: { flexGrow: 1, paddingHorizontal: 18, maxWidth: 640, width: '100%', alignSelf: 'center' }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 30 }, question: { color: colors.ink, fontSize: 24, lineHeight: 29, fontWeight: '800', textAlign: 'center', marginTop: 18 }, helper: { color: colors.inkMuted, fontSize: 14, lineHeight: 21, textAlign: 'center', maxWidth: 280, marginTop: 9 }, suggestions: { width: '100%', maxWidth: 310, gap: 8, marginTop: 25 }, suggestion: { minHeight: 48, borderRadius: 16, backgroundColor: colors.glass, borderWidth: 1, borderColor: '#fff', justifyContent: 'center', paddingHorizontal: 16 }, suggestionText: { color: colors.inkMuted, fontSize: 13, fontWeight: '600' }, demo: { color: colors.inkFaint, fontSize: 10, marginTop: 20 }, thread: { gap: 14, paddingTop: 18, paddingBottom: 18 }, bubble: { maxWidth: '88%', padding: 14, borderRadius: 19 }, user: { alignSelf: 'flex-end', backgroundColor: colors.green, borderBottomRightRadius: 6 }, ai: { alignSelf: 'flex-start', paddingLeft: 3 }, message: { color: colors.ink, fontSize: 15, lineHeight: 23 }, action: { minHeight: 44, marginTop: 8, flexDirection: 'row', alignItems: 'center', gap: 7 }, actionText: { color: colors.green, fontSize: 12, fontWeight: '800' }, thinking: { alignSelf: 'flex-start', flexDirection: 'row', gap: 10, alignItems: 'center', padding: 13, borderRadius: 18, backgroundColor: colors.glass }, thinkingText: { color: colors.inkMuted, fontSize: 12 }, composerWrap: { paddingHorizontal: 16, paddingTop: 8, maxWidth: 640, width: '100%', alignSelf: 'center' }, composer: { minHeight: 58, borderRadius: 22, backgroundColor: colors.glass, borderWidth: 1, borderColor: '#fff', paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 10 }, input: { flex: 1, color: colors.ink, fontSize: 15, maxHeight: 88 }, send: { width: 42, height: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.green }, whatsapp: { minHeight: 42, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 }, whatsappText: { color: colors.green, fontSize: 11, fontWeight: '700' } });
