import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { PageHeader, Screen } from '@/src/components/ui';
import { useAppState } from '@/src/state/AppState';
import { colors, radius } from '@/src/theme';
const filters = ['Upcoming', 'Current', 'Past'] as const;
export default function BookingsScreen() {
  const { bookings, properties } = useAppState(); const [filter, setFilter] = useState<typeof filters[number]>('Upcoming');
  const visible = useMemo(() => bookings.filter((b) => filter === 'Upcoming' ? b.status === 'Confirmed' : filter === 'Current' ? b.status === 'In house' : b.status === 'Completed'), [bookings, filter]);
  return <Screen><PageHeader title="Bookings" subtitle="Every stay, quietly organised." /><View style={styles.filters}>{filters.map((item) => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: filter === item }} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.active]}><Text style={[styles.filterText, filter === item && styles.activeText]}>{item}</Text></Pressable>)}</View>
    <View style={styles.list}>{visible.map((booking) => { const property = properties.find((p) => p.id === booking.propertyId); return <Pressable key={booking.id} onPress={() => router.push(`/booking/${booking.id}`)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><Image source={property?.image} style={styles.image} /><View style={styles.copy}><View style={styles.top}><View><Text style={styles.guest}>{booking.guest}</Text><Text style={styles.property}>{property?.name}</Text></View><Text style={styles.value}>{booking.value}</Text></View><Text style={styles.dates}>{booking.dates} · {booking.nights} nights</Text><View style={styles.bottom}><Text style={styles.status}>{booking.status}</Text><Text style={styles.arrow}>›</Text></View></View></Pressable>; })}{visible.length === 0 && <Text style={styles.empty}>No stays in this view.</Text>}</View>
  </Screen>;
}
const styles = StyleSheet.create({ filters: { flexDirection: 'row', padding: 4, borderRadius: 18, backgroundColor: 'rgba(232,230,236,.76)', marginTop: 14 }, filter: { flex: 1, minHeight: 44, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, active: { backgroundColor: '#fff', shadowColor: '#201936', shadowOpacity: .06, shadowRadius: 8, elevation: 2 }, filterText: { color: colors.inkMuted, fontSize: 12, fontWeight: '700' }, activeText: { color: colors.ink }, list: { gap: 14, marginTop: 22 }, card: { minHeight: 150, borderRadius: radius.xl, overflow: 'hidden', backgroundColor: colors.surface, flexDirection: 'row' }, image: { width: 112 }, copy: { flex: 1, padding: 16 }, top: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, guest: { color: colors.ink, fontSize: 16, fontWeight: '800' }, property: { color: colors.inkMuted, fontSize: 11, marginTop: 4 }, value: { color: colors.ink, fontSize: 14, fontWeight: '800' }, dates: { color: colors.inkMuted, fontSize: 12, marginTop: 18 }, bottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 15 }, status: { color: colors.green, backgroundColor: colors.greenSoft, fontSize: 10, fontWeight: '800', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 9 }, arrow: { color: colors.inkFaint, fontSize: 23 }, pressed: { opacity: .75, transform: [{ scale: .99 }] }, empty: { color: colors.inkMuted, textAlign: 'center', marginTop: 40 } });
