import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Orb, PageHeader, Screen } from '@/src/components/ui';
import { useAppState } from '@/src/state/AppState';
import { colors, radius } from '@/src/theme';
const suggestions = ["Today's check-ins", 'Message a guest', 'Update pricing', 'Manage availability'];
export default function HomeScreen() {
  const { bookings, properties, setAssistantDraft, connected } = useAppState();
  const openAI = (prompt?: string) => { if (prompt) setAssistantDraft(prompt); router.push('/ai'); };
  return <Screen><PageHeader title="Good morning, Anotida." subtitle="Tuesday, 9 September" action={<Pressable accessibilityRole="button" accessibilityLabel="Open settings" onPress={() => router.push('/more')} style={styles.avatar}><Text style={styles.avatarText}>AY</Text></Pressable>} />
    <Text style={styles.summary}>2 guests are arriving today.{`\n`}Everything is ready.</Text>
    <Pressable accessibilityRole="button" onPress={() => openAI()} style={({ pressed }) => [styles.command, pressed && styles.pressed]}><Orb size={38} /><Text style={styles.commandText}>What can I take care of?</Text><Ionicons name="mic-outline" size={20} color={colors.green} /></Pressable>
    <View style={styles.chips}>{suggestions.map((item) => <Pressable key={item} accessibilityRole="button" onPress={() => openAI(item)} style={styles.chip}><Text style={styles.chipText}>{item}</Text></Pressable>)}</View>
    {!connected && <View style={styles.preview}><Ionicons name="information-circle-outline" size={17} color={colors.green} /><Text style={styles.previewText}>Sample workspace · no live booking channel connected</Text></View>}
    <View style={styles.sectionHead}><Text style={styles.section}>Today</Text><Pressable onPress={() => router.push('/bookings')}><Text style={styles.link}>View bookings</Text></Pressable></View>
    <View style={styles.today}>{bookings.slice(0,2).map((booking) => { const property = properties.find((p) => p.id === booking.propertyId); return <Pressable key={booking.id} accessibilityRole="button" onPress={() => router.push(`/booking/${booking.id}`)} style={({ pressed }) => [styles.stay, pressed && styles.pressed]}><Image source={property?.image} style={styles.image} /><View style={styles.stayCopy}><View style={styles.labelRow}><Text style={styles.pill}>{booking.status === 'In house' ? 'Check-out' : 'Check-in'}</Text><Text style={styles.time}>{booking.checkIn.split('·')[1]?.trim()}</Text></View><Text style={styles.guest}>{booking.guest}</Text><Text style={styles.meta}>{property?.name} · {booking.nights} nights</Text><Text style={styles.ready}>{booking.id === 'sarah' ? 'Check-in instructions sent ✓' : 'Cleaning scheduled 11:30'}</Text></View></Pressable>; })}</View>
  </Screen>;
}
const styles = StyleSheet.create({ avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#fff', fontSize: 12, fontWeight: '900' }, summary: { color: '#3A3A38', fontSize: 17, lineHeight: 27, marginTop: 14 }, command: { minHeight: 72, borderRadius: 23, backgroundColor: colors.glass, borderWidth: 1, borderColor: '#fff', paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 23, shadowColor: '#30275B', shadowOpacity: .08, shadowRadius: 20, shadowOffset: { width: 0, height: 8 }, elevation: 4 }, commandText: { flex: 1, color: colors.inkFaint, fontSize: 16 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 13 }, chip: { minHeight: 40, borderRadius: 20, backgroundColor: 'rgba(255,255,255,.82)', paddingHorizontal: 14, justifyContent: 'center', borderWidth: 1, borderColor: '#fff' }, chipText: { color: colors.inkMuted, fontSize: 12, fontWeight: '600' }, preview: { flexDirection: 'row', gap: 7, marginTop: 17, alignItems: 'center' }, previewText: { color: colors.inkMuted, fontSize: 11 }, sectionHead: { marginTop: 28, marginBottom: 13, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, section: { color: colors.inkFaint, fontSize: 11, fontWeight: '800', letterSpacing: 1.2, textTransform: 'uppercase' }, link: { color: colors.green, fontSize: 12, fontWeight: '700' }, today: { gap: 12 }, stay: { minHeight: 104, borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.surface, flexDirection: 'row' }, image: { width: 98, height: 112 }, stayCopy: { flex: 1, padding: 13 }, labelRow: { flexDirection: 'row', alignItems: 'center', gap: 8 }, pill: { color: colors.green, backgroundColor: colors.greenSoft, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, textTransform: 'uppercase', fontSize: 9, fontWeight: '800', letterSpacing: .8 }, time: { color: colors.inkFaint, fontSize: 11 }, guest: { color: colors.ink, fontSize: 15, fontWeight: '800', marginTop: 8 }, meta: { color: colors.inkMuted, fontSize: 11, marginTop: 3 }, ready: { color: colors.green, fontSize: 11, fontWeight: '600', marginTop: 7 }, pressed: { opacity: .78, transform: [{ scale: .99 }] } });
