import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ImageBackground, Pressable, StyleSheet, Text, View } from 'react-native';
import { PageHeader, Screen } from '@/src/components/ui';
import { useAppState } from '@/src/state/AppState';
import { colors } from '@/src/theme';
export default function ListingsScreen() {
  const { properties, reviews } = useAppState();
  return <Screen><PageHeader title="My Listings" subtitle="Your Johannesburg portfolio" action={<Pressable style={styles.add}><Ionicons name="add" size={20} color={colors.ink} /></Pressable>} /><View style={styles.list}>{properties.map((p, i) => { const score = reviews.filter((r) => r.propertyId === p.id).reduce((a,r) => a+r.rating,0) / Math.max(1,reviews.filter((r) => r.propertyId === p.id).length); return <Pressable key={p.id} onPress={() => router.push(`/property/${p.id}`)} style={({ pressed }) => [styles.card, pressed && { opacity: .83, transform: [{ scale: .995 }] }]}><ImageBackground source={p.image} style={styles.image}><View style={styles.shade} /><View style={styles.active}><View style={styles.dot} /><Text style={styles.activeText}>Active</Text></View><View style={styles.overlay}><Text style={styles.name}>{p.name}</Text><Text style={styles.area}>{p.area}</Text><View style={styles.meta}><Text style={styles.price}>{i ? 'R1,650' : 'R1,450'} / night</Text><Text style={styles.rating}>{score.toFixed(2)} ★</Text></View></View></ImageBackground></Pressable>; })}</View></Screen>;
}
const styles = StyleSheet.create({ add: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, list: { gap: 18, marginTop: 12 }, card: { height: 290, borderRadius: 26, overflow: 'hidden', backgroundColor: '#ddd' }, image: { flex: 1, justifyContent: 'flex-end' }, shade: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(0,0,0,.18)' }, active: { position: 'absolute', top: 15, right: 15, minHeight: 34, borderRadius: 17, paddingHorizontal: 12, backgroundColor: 'rgba(255,255,255,.9)', flexDirection: 'row', alignItems: 'center', gap: 7 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#57A96F' }, activeText: { color: colors.ink, fontSize: 10, fontWeight: '800' }, overlay: { padding: 18 }, name: { color: '#fff', fontSize: 23, fontWeight: '900', letterSpacing: -.5 }, area: { color: 'rgba(255,255,255,.75)', fontSize: 12, marginTop: 4 }, meta: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 14 }, price: { color: '#fff', fontSize: 13, fontWeight: '700' }, rating: { color: '#fff', fontSize: 13, fontWeight: '700' } });
