import { Ionicons } from '@expo/vector-icons';
import * as Linking from 'expo-linking';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Eyebrow, Screen, ScreenTitle, StatusDot } from '@/src/components/ui';
import { whatsappConfig } from '@/src/config';
import { useAppState } from '@/src/state/AppState';
import { colors, radius, spacing } from '@/src/theme';

const rows = [
  { label: 'Approvals', detail: 'Review staged listing changes', icon: 'shield-checkmark-outline' as const, route: '/approvals' },
  { label: 'Activity & audit', detail: 'Trace actions and safe failures', icon: 'pulse-outline' as const, route: '/activity' },
  { label: 'Workspace connection', detail: 'Pair or inspect connection health', icon: 'link-outline' as const, route: '/connect' },
];
export default function MoreScreen() {
  const { approvals, connected, replayOnboarding, selectApproval } = useAppState(); const pendingApprovals = approvals.filter((item) => item.status === 'pending'); const pending = pendingApprovals.length;
  const openRow = (label: string, route: string) => { if (label === 'Approvals' && pendingApprovals[0]) selectApproval(pendingApprovals[0].id); router.push(route as never); };
  return <Screen><Eyebrow>Control centre</Eyebrow><ScreenTitle>More</ScreenTitle><Text style={styles.intro}>Approvals, connection health and the record behind every action.</Text>
    <View style={styles.health}><View style={styles.healthTop}><StatusDot tone={connected ? 'green' : 'neutral'} /><Text style={styles.healthTitle}>{connected ? 'Your workspace is connected' : 'Preview mode'}</Text></View><Text style={styles.healthBody}>{connected ? 'Your latest hosting data is ready. VirtuHost will always show when a booking channel confirms a change.' : 'Sample data only. No booking channel, listing or live AI service is connected.'}</Text><View style={styles.healthMeta}><Text style={styles.metaText}>{pending} pending approval{pending === 1 ? '' : 's'}</Text><Text style={styles.metaText}>Africa/Johannesburg</Text></View></View>
    <View style={styles.rows}>{rows.map((row) => <Pressable key={row.label} accessibilityRole="button" onPress={() => openRow(row.label, row.route)} style={({ pressed }) => [styles.row, pressed && { opacity: 0.65 }]}><View style={styles.icon}><Ionicons name={row.icon} size={20} color={colors.green} /></View><View style={styles.flex}><Text style={styles.rowTitle}>{row.label}</Text><Text style={styles.rowDetail}>{row.detail}</Text></View>{row.label === 'Approvals' && pending > 0 && <View style={styles.badge}><Text style={styles.badgeText}>{pending}</Text></View>}<Ionicons name="chevron-forward" size={18} color={colors.inkFaint} /></Pressable>)}</View>
    <Text style={styles.section}>Assistant access</Text><Pressable accessibilityRole="button" onPress={() => Linking.openURL(whatsappConfig.url)} style={styles.whatsapp}><Ionicons name="logo-whatsapp" size={21} color="#fff" /><View style={styles.flex}><Text style={styles.whatsappTitle}>Continue in WhatsApp</Text><Text style={styles.whatsappBody}>{whatsappConfig.isConfigured ? 'Open the approved VirtuHost conversation' : 'Opens a recipient-free demo draft'}</Text></View><Ionicons name="open-outline" size={18} color="#fff" /></Pressable>
    <Pressable accessibilityRole="button" onPress={() => { replayOnboarding(); router.navigate('/'); }} style={styles.replay}><Ionicons name="refresh-outline" size={18} color={colors.ink} /><Text style={styles.replayText}>Replay onboarding</Text></Pressable>
  </Screen>;
}
const styles = StyleSheet.create({ intro: { color: colors.inkMuted, fontSize: 14, lineHeight: 21, marginTop: 8 }, health: { marginTop: 24, backgroundColor: colors.surfaceSoft, borderRadius: radius.xl, padding: 20 }, healthTop: { flexDirection: 'row', alignItems: 'center', gap: 8 }, healthTitle: { color: colors.ink, fontSize: 15, fontWeight: '900' }, healthBody: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 10 }, healthMeta: { borderTopWidth: 1, borderTopColor: '#D7E0DB', marginTop: 15, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between' }, metaText: { color: colors.inkMuted, fontSize: 10, fontWeight: '700' }, rows: { marginTop: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line }, row: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: colors.line }, icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.greenSoft, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, rowTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' }, rowDetail: { color: colors.inkMuted, fontSize: 11, marginTop: 4 }, badge: { minWidth: 24, height: 24, borderRadius: 8, backgroundColor: colors.amberSoft, alignItems: 'center', justifyContent: 'center' }, badgeText: { color: colors.amber, fontSize: 11, fontWeight: '900' }, section: { color: colors.ink, fontSize: 17, fontWeight: '900', marginTop: 28, marginBottom: 12 }, whatsapp: { minHeight: 72, borderRadius: radius.lg, backgroundColor: colors.green, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 13 }, whatsappTitle: { color: '#fff', fontSize: 14, fontWeight: '900' }, whatsappBody: { color: '#D5EBDF', fontSize: 10, marginTop: 3 }, replay: { minHeight: 54, marginTop: 12, borderRadius: radius.md, backgroundColor: '#fff', borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, replayText: { color: colors.ink, fontSize: 13, fontWeight: '800' } });
