import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, EmptyState, Eyebrow, Screen, ScreenTitle } from '@/src/components/ui';
import { useAppState } from '@/src/state/AppState';
import { colors, radius, spacing } from '@/src/theme';

export default function ReviewsScreen() {
  const { reviews, properties, setAssistantDraft, setAssistantReview } = useAppState();
  const [filter, setFilter] = useState('all');
  const visible = useMemo(() => reviews.filter((review) => filter === 'all' || review.propertyId === filter), [filter, reviews]);
  const draft = (id: string) => { const review = reviews.find((item) => item.id === id); if (!review) return; setAssistantReview(id); setAssistantDraft('Draft a reply to this review'); router.navigate('/'); };
  return <Screen><Eyebrow>Guest sentiment</Eyebrow><ScreenTitle>Reviews</ScreenTitle><Text style={styles.intro}>Sample feedback across your Johannesburg portfolio.</Text>
    <View style={styles.summary}><View><Text style={styles.rating}>4.9</Text><View style={styles.stars}>{[1,2,3,4,5].map((n) => <Ionicons key={n} name="star" size={14} color={colors.green} />)}</View></View><View style={styles.summaryCopy}><Text style={styles.summaryTitle}>Excellent stays</Text><Text style={styles.summaryText}>{reviews.length} sample reviews shown in this preview</Text></View></View>
    <View style={styles.filters}><Pressable accessibilityRole="button" accessibilityState={{ selected: filter === 'all' }} onPress={() => setFilter('all')} style={[styles.filter, filter === 'all' && styles.filterActive]}><Text style={[styles.filterText, filter === 'all' && styles.filterTextActive]}>All</Text></Pressable>{properties.map((property) => <Pressable accessibilityRole="button" accessibilityState={{ selected: filter === property.id }} key={property.id} onPress={() => setFilter(property.id)} style={[styles.filter, filter === property.id && styles.filterActive]}><Text numberOfLines={1} style={[styles.filterText, filter === property.id && styles.filterTextActive]}>{property.name.replace('Rosebank ', '').replace('Sandton ', '')}</Text></Pressable>)}</View>
    {visible.length === 0 ? <Card><EmptyState icon="star-outline" title="No reviews here yet" body="New guest feedback will appear after a connected provider confirms it." /></Card> : <View style={styles.list}>{visible.map((review) => <Card key={review.id} style={styles.review}><View style={styles.reviewTop}><View style={styles.initial}><Text style={styles.initialText}>{review.reviewer[0]}</Text></View><View style={styles.flex}><Text style={styles.reviewer}>{review.reviewer}</Text><Text style={styles.meta}>{properties.find((p) => p.id === review.propertyId)?.name} · {review.date}</Text></View><Text style={styles.score}>{review.rating.toFixed(1)}</Text></View><Text style={styles.excerpt}>{review.excerpt}</Text><View style={styles.reviewBottom}><View><Text style={styles.source}>{review.source}</Text><Text style={[styles.response, review.responseStatus === 'Needs reply' && { color: colors.amber }]}>{review.responseStatus}</Text></View>{review.responseStatus === 'Needs reply' && <Pressable accessibilityRole="button" onPress={() => draft(review.id)} style={styles.draft}><Ionicons name="sparkles-outline" size={15} color={colors.green} /><Text style={styles.draftText}>Draft reply</Text></Pressable>}</View></Card>)}</View>}
  </Screen>;
}
const styles = StyleSheet.create({ intro: { color: colors.inkMuted, fontSize: 14, lineHeight: 21, marginTop: 8 }, summary: { marginTop: 24, paddingVertical: 22, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 22 }, rating: { color: colors.ink, fontSize: 38, fontWeight: '900', letterSpacing: -1.2 }, stars: { flexDirection: 'row', gap: 2, marginTop: 3 }, summaryCopy: { flex: 1 }, summaryTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, summaryText: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 4 }, filters: { flexDirection: 'row', gap: 8, marginVertical: 20 }, filter: { flex: 1, minHeight: 44, borderRadius: 12, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 }, filterActive: { backgroundColor: colors.ink }, filterText: { color: colors.inkMuted, fontSize: 12, fontWeight: '800' }, filterTextActive: { color: '#fff' }, list: { gap: 12 }, review: { padding: 17 }, reviewTop: { flexDirection: 'row', alignItems: 'center', gap: 11 }, initial: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.greenSoft, alignItems: 'center', justifyContent: 'center' }, initialText: { color: colors.green, fontWeight: '900' }, flex: { flex: 1 }, reviewer: { color: colors.ink, fontSize: 14, fontWeight: '900' }, meta: { color: colors.inkMuted, fontSize: 12, marginTop: 3 }, score: { color: colors.ink, fontSize: 14, fontWeight: '900' }, excerpt: { color: colors.ink, fontSize: 14, lineHeight: 22, marginTop: 15 }, reviewBottom: { marginTop: 15, paddingTop: 13, borderTopWidth: 1, borderTopColor: colors.line, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, source: { color: colors.inkFaint, fontSize: 12, fontWeight: '700' }, response: { color: colors.green, fontSize: 12, fontWeight: '900', marginTop: 3 }, draft: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: colors.line, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 7 }, draftText: { color: colors.green, fontSize: 12, fontWeight: '900' } });
